import 'package:entrevista_ff/src/repository/algorithm/btree.dart';
import 'package:entrevista_ff/src/util/synonim.dart';

const Map<String, String> synonimGroup = {
  '01': 'fundamental',
  '02': 'igual',
  '03': 'plazo',
  '04': 'exito',
  '05': 'capacidad',
  '06': 'grupo',
  '07': 'momento',
  '08': 'parte',
  '09': 'excepcional',
  '10': 'humor',
  '11': 'opinion',
  '12': 'entorno',
  '13': 'principio',
  '14': 'forma',
  '15': 'poco',
  '16': 'etica',
  '17': 'mentor',
  '18': 'inteligente',
  '19': 'universidad',
  '20': 'software',
};

class SynonimWord {
  BTree tree = BTree(3);
  
  List<Synonim> synonims = [
    Synonim('fundamental', '01'),
    Synonim('principal', '01'),
    Synonim('igual', '02'),
    Synonim('semejante', '02'),
    Synonim('plazo', '03'),
    Synonim('tiempo', '03'),
    Synonim('periodo', '03'),
    Synonim('intervalo', '03'),
    Synonim('exito', '04'),
    Synonim('logro', '04'),
    Synonim('victoria', '04'),
    Synonim('triunfo', '04'),
    Synonim('capacidad', '05'),
    Synonim('talento', '05'),
    Synonim('competencia', '05'),
    Synonim('grupo', '06'),
    Synonim('equipo', '06'),
    Synonim('momento', '07'),
    Synonim('instante', '07'),
    Synonim('ocasion', '07'),
    Synonim('parte', '08'),
    Synonim('pedazo', '08'),
    Synonim('trozo', '08'),
    Synonim('porcion', '08'),
    Synonim('excepcional', '09'),
    Synonim('singular', '09'),
    Synonim('extraordinario', '09'),
    Synonim('insolito', '09'),
    Synonim('humor', '10'),
    Synonim('temple', '10'),
    Synonim('caracter', '10'),
    Synonim('opinion', '11'),
    Synonim('juicio', '11'),
    Synonim('criterio', '11'),
    Synonim('entorno', '12'),
    Synonim('ambiente', '12'),
    Synonim('principio', '13'),
    Synonim('comienzo', '13'),
    Synonim('inicio', '13'),
    Synonim('forma', '14'),
    Synonim('manera', '14'),
    Synonim('modo', '14'),
    Synonim('estilo', '14'),
    Synonim('poco', '15'),
    Synonim('escaso', '15'),
    Synonim('corto', '15'),
    Synonim('etica', '16'),
    Synonim('moral', '16'),
    Synonim('mentor', '17'),
    Synonim('guia', '17'),
    Synonim('inteligente', '18'),
    Synonim('sabio', '18'),
    Synonim('ingenioso', '18'),
    Synonim('universidad', '19'),
    Synonim('instituto', '19'),
    Synonim('escuela', '19'),
    Synonim('academia', '19'),
    Synonim('facultad', '19'),
    Synonim('software', '20'),
    Synonim('aplicacion', '20'),
    Synonim('programa', '20'),
  ];

  BTree sinonimos() {
    for (Synonim synonim_word in synonims) {
      tree.insert(tree, synonim_word);
    }
    return tree;
  }
}
