name: entrevista_ff
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.11
  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.14
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  meta: ^1.1.7
  font_awesome_flutter: ^8.5.0
  flutter_auth_buttons: ^0.6.0
  flutter_offline: "^0.3.0"
  data_connection_checker: ^0.3.4
  flutter_custom_clippers: ^1.1.0
  dart_random_choice: ^0.0.2
  auto_size_text: ^2.1.0
  bubble: ^1.1.9+1
  connectivity: ^0.4.5+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  pedantic:


dependency_overrides:
  flutter_offline: "^0.3.0"
  connectivity: ^0.4.5+7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Vollkorn
      fonts:
        - asset: fonts/Vollkorn-Regular.ttf
        - asset: fonts/Vollkorn-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
